### ISSUE TITLE
Disable user adding new line while adding username in when Signing Up

### ISSUE THREAD

**Issue by MamboBryan** [JoelKanyi/Joomia#11]
This is the current behaviour when someone presses enter while adding username. 

![Screenshot_2022-06-22-07-41-09-328_com.kanyideveloper.joomia.jpg](https://user-images.githubusercontent.com/40160345/174945152-422bc452-b524-49e3-912a-9c9f7b341a07.jpg)

**Comment by JoelKanyi** [comment]
Done
