### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by matus-tomlein** [JoelKanyi/Joomia#17]
Could you please add a license to the repository? It would be very useful to use this as a demo app for our purposes, but we don't know whether this is permitted.

**Comment by JoelKanyi** [comment]
Sure @matus-tomlein let me add license.

**Comment by JoelKanyi** [comment]
Added, feel free to inquire anything from me

**Comment by matus-tomlein** [comment]
Thank you @JoelKanyi for resolving this so quickly!
